@startuml
class InputLayer {
    +253
}

class Conv1D_1 {
    +Filters: 16-128 (tunable)
    +Kernel Size: 3
    +Activation: ReLU
}

class Conv1D_2 {
    +Filters: 16-128 (tunable)
    +Kernel Size: 3
    +Activation: ReLU
}

class Dropout {
    +Rate: 0.0-0.5 (tunable)
}

class OutputLayer {
    + 6
}

InputLayer -right-> Conv1D_1 : "Data Flow"
Conv1D_1 -right-> MaxPooling1D : "Data Flow"
MaxPooling1D -right-> Conv1D_2 : "Data Flow"
Conv1D_2 -right-> GlobalMaxPooling1D : "Data Flow"
GlobalMaxPooling1D -right-> Dropout : "Data Flow"
Dropout -right-> OutputLayer : "Data Flow"

@enduml
